### ISSUE TITLE
Is there a tutorial how to use this with StaxRip?

### ISSUE THREAD

**Issue by Abu3safeer** [Irrational-Encoding-Wizardry/fvsfunc#4]
Hello everyone,

I am trying to use Insertsign() function, but I don't know if there an option of it, or I should write it manually.

![image](https://user-images.githubusercontent.com/12091003/51720270-f8d0ed80-205d-11e9-9a75-38d17a0dad31.png)

![image](https://user-images.githubusercontent.com/12091003/51720281-09816380-205e-11e9-97bd-b127d6f35a0d.png)

![image](https://user-images.githubusercontent.com/12091003/51720328-30d83080-205e-11e9-9700-3d184c4b3d52.png)

What code I want to apply?
```
Afx=directShowSource("file")
Insertsign(last,afx,0,0)
```

If you don't accept this type of questions, could you guide me where can I ask this question?

**Comment by Frechdachs** [comment]
I personally never used StaxRip and also can't test it since I currently don't have a Windows installation.

However, the Vapoursynth functions in this script can be used just like any other Vapoursynth function. So if you know how to use Vapoursynth inside StaxRip, there should be no problem.

So this is more of a StaxRip related question and should be directed at them.

**Comment by Abu3safeer** [comment]
Thank you.
